### ISSUE TITLE
CJS support

### ISSUE THREAD

**Issue by mariandaniel24** [iway1/trpc-panel#32]
I've been trying to get `trpc-panel` running on a node server without any transpilation step, I'm only using the `tsc` to compile my code.

The way I managed to work around the issue is by shamefully patching the package, mainly did that to test `trpc-panel` in a semi-large codebase, which by the way is quite awesome for debugging/DX.
AFAIK this it shouldn't break existing applications that are ESM, but I might be wrong about that?

Here's the patch I used:
```diff
diff --git a/package.json b/package.json
index 13d820100c8ad63ad5bb77db97ae708767480054..4238eafc2fdee1e49091f7424db05f66302cb1af 100644
--- a/package.json
+++ b/package.json
@@ -5,7 +5,6 @@
   "main": "lib/index.js",
   "module": "lib/index.mjs",
   "typings": "lib/src/index.d.ts",
-  "type": "module",
   "scripts": {
     "test": "jest",
     "test:watch": "jest --watch",
     ```

**Comment by iway1** [comment]
> which by the way is quite awesome for debugging/DX.

awesome 😃

And yeahh this is something I've been meaning to fix. I'll apply this patch and get a new release shortly
