### ISSUE TITLE
[BUG] A value of 0 is not accepted as a valid number field value, minus sign cannot be entered as first character

### ISSUE THREAD

**Issue by jedzej** [iway1/trpc-panel#36]
Looks like numbers are incorrectly parsed in the input field. It has 2 manifestations:
1. When trying to enter `0`, the field empties itself.
2. When trying to enter `-` to be followed with some numbers, the field empties itself (although you can overcome it by typing minus after typing the number)

Manifestation 1 is more severe, since it has no workaround.

Affected field:
![image](https://user-images.githubusercontent.com/57070/212482887-60ee8293-10e4-4235-b003-6633d2e748f8.png)

Reproduction repository (small fork from test app):
https://github.com/jedzej/trpc-panel-bug-repro/commit/62857ae7f95bec78e540327a41b13a03cf6a3a79

**Comment by iway1** [comment]
Fixed in v1.2.6. Thanks for the issue report!
