### ISSUE TITLE
Panel Not Updating After Code Changes

### ISSUE THREAD

**Issue by khill-fbmc** [iway1/trpc-panel#42]
I am loving this panel, thank you. Am I missing something with the refresh? I add `.optional()` to one of my inputs, and refresh the panel, but it is still marked as required. 

My only solution so far is to shutdown the dev server and restart it :(

Is there an easier way?

**Comment by rklubenspies** [comment]
Also having this issue when using `trpc-panel` in an Nx monorepo.

**Comment by pmenta** [comment]
yep, in #54 i added a option to disable caching the html of the panel, so everytime you refresh the page the routes will be updated

so your api/panel code will be like
`export default function handler(_: NextApiRequest, res: NextApiResponse) {
  res.status(200).send(renderTrpcPanel(appRouter, {
    url: `${env.AUTH0_BASE_URL}/api/trpc`,
    transformer: "superjson",
    cache: false
  }));
}`

**Comment by pmenta** [comment]
the last PR #58 of @iway1 disable cache by default, i think this issue can be closed
