### ISSUE TITLE
BigInt crashes frontend with `TypeError: BigInt value can't be serialized in JSON`.

### ISSUE THREAD

**Issue by ben-xD** [iway1/trpc-panel#55]
Thanks for this library! It's great for productivity - I'm just getting started.

I get an error in the browser when the API returns an object that contains a `BigInt`. For example, the JSON looks like:
```
[{"result":{"data":{"json":[{"id":"bob","createdAt":{"seconds":"1680535620","nanos":737587000}}],"meta":{"values":{"0.createdAt.seconds":["bigint"]}}}}}]
```

I'm using superjson. It looks like both superjson and trpc-panel are documented to support BigInt. However, returning `BigInt` causes the app to go into a full white screen.

**Do you know what I can try to fix this?**

Thanks 🙏

![CleanShot 2023-04-03 at 16 53 08](https://user-images.githubusercontent.com/24711048/229562604-a3bb616d-ef70-4ed7-b9d4-4b34f1301ffe.png)

**Comment by iway1** [comment]
makes sense that this is happening, the return value of the procedure gets passed to `JSON.stringify()`. Definitely want to fix this, will need to use something else for converting the response into a string.

thanks!

**Comment by iway1** [comment]
should be fixed in new version

**Comment by ben-xD** [comment]
Thanks a lot! 🙏
