### ISSUE TITLE
feature request: toggle viewing sidebar/minimap

### ISSUE THREAD

**Issue by SeanCassiere** [iway1/trpc-panel#57]
Nothing too crazy, just want to toggle the sidebar/minimap shown on the left for two reasons:
1. I don't really use it.
2. When procedure names are long the layout tends to shift drastically. (please see screenshots below)

![image](https://user-images.githubusercontent.com/33615041/229685229-e67b5433-bad6-4ae0-8859-cb5a18e5fc7b.png)
![image](https://user-images.githubusercontent.com/33615041/229685540-f5944a0f-aa5f-46a1-898d-b75d7bd7a874.png)

**Comment by iway1** [comment]
This would be cool, open to PRs

**Comment by SeanCassiere** [comment]
@iway1 Sounds good.

Got any preferences as to the design and where you'd want the toggle button to go?

**Comment by SeanCassiere** [comment]
Currently, in dev, I'm simply reusing the Chevron in the `TopBar` to toggle the state of the sidebar.

![image](https://user-images.githubusercontent.com/33615041/232645053-6c9ec73a-0905-4d34-8562-9d926fe18cea.png)
![image](https://user-images.githubusercontent.com/33615041/232645097-ae2cd983-15e2-43f0-9003-88b3d25d06fc.png)

Note:
* By default, the sidebar is open.
* The sidebar open state is NOT persisted and will be set to default on refresh.

**Comment by iway1** [comment]
@SeanCassiere Nice yeah I think that looks good. 

Persistence would be nice to have I think but not totally necessary. I'm wondering whether people are going to want to open and close it frequently

**Comment by SeanCassiere** [comment]
@iway1 Personally for me (regarding persistence), as I like having descriptive procedure names in my routers, I'd probably always close the minimap on launch.

If you are fine with it, I could add a stripped-down version of this [useLocalStorage hook](https://usehooks-ts.com/react-hook/use-local-storage) for persistence, using a key like `trpc-panel.show-minimap`.
