### ISSUE TITLE
Long Zod Input description text breaks Flex Layout

### ISSUE THREAD

**Issue by khill-fbmc** [iway1/trpc-panel#59]
I didn't notice until I tried copy-pasting some long text into the ~meta~ zod input descriptions...

![image](https://user-images.githubusercontent.com/107003416/230108970-d944c44e-37b2-4b1b-a490-4f661ef3299f.png)

I see that the layout is two separate flex divs... I feel that a grid layout would work better than `div` + `ul`

**Comment by iway1** [comment]
Thanks for the reproduction.

Adding a contribution guide is a really good idea! 

Having the `dev-app` as part of the repo makes it pretty easy to work on the project locally but it's not obvious at all how to get it up and running. I'll put something together in the next couple days

**Comment by iway1** [comment]
@khill-fbmc I did an overhaul of the `dev-app` now it should be as easy as possible to run `trpc-panel` locally to work on the library. See the new contribution guide at https://github.com/iway1/trpc-panel/blob/main/CONTRIBUTING.md

Let me know if you have any issues getting it up an running, should just be able to install dependencies and run the dev-app. Feel free to add any additional recommendation about making contributions easier, if you have any 🙏

Looking at a fix for the layout issue

**Comment by iway1** [comment]
very cool! :)
