### ISSUE TITLE
Remove `fs": "^0.0.1-security"` from package.json?

### ISSUE THREAD

**Issue by guybarnard** [iway1/trpc-panel#66]
Is it possible to remove the `fs": "^0.0.1-security"` from package.json?

This is an artifact of an old repository on npm that used to include malware, but now points to a broken package with a missing implementation.  

While it works fine in classic npm-based bundlers it breaks when installing using `pnpm` and using `vite` or `esbuild` (and in particular `astro` framework based on these).  Removing the line immediately fixes those bundlers.      Using the pnpm patch doesn't help as pnpm adds `fs` before applying the patch.    Using the vite config to mark `fs` as external helps, but in astro the SSR pre-bundle still trips up if the broken `fs` package is in the catch.  It errors saying it can't find the entrypoint of the `fs` package.

Many thanks for an amazing capability in `trpc-panel`

**Comment by iway1** [comment]
Yep will get rid of that, thanks for the info :)
