### ISSUE TITLE
`undefined` / `null` checks for perhaps poorly formed routers

### ISSUE THREAD

**Issue by AshSimmonds** [iway1/trpc-panel#7]
As mentioned on Theo's Discord - there were a few places I had to add in some basic null checks to stop it crashing. It's likely because it's running on some older code which I haven't fully updated to proper Zod usage or something - but point remains it was able to crash this extension.

I just wanted to get it working for me and move on for now as have a deadline, so here's the modded file that ends up in `\node_modules\trpc-panel\lib\index.mjs`, and an ugly diff screenshot.

[index.mjs.txt](https://github.com/iway1/trpc-panel/files/10210382/index.mjs.txt)

![screenshot_20221213-034637_GitHubDesktop_Mf4QQuTTvm](https://user-images.githubusercontent.com/9034041/207110704-f9fbd9bf-447f-4bb5-a550-c40ed358458e.png)

**Comment by iway1** [comment]
Just finished a refactor of this section of the codebase... we're now using zod for internal type validation which should make any of these types of issues much less likely to happen. Going to close b/c I'm pretty sure it should solve this (at least the crashing), although I wasn't able to reproduce in the first place. Will be included in my 

Haven't had the chance to add in better error messages quite yet. But definitely still on my radar.

Feel free too reopen if you run into similar issues! Thanks.
