### ISSUE TITLE
DEV: Query re-runs if code changes and reload occurs

### ISSUE THREAD

**Issue by AshSimmonds** [iway1/trpc-panel#8]
Possibly a non-issue, but if you're doing some "endpoint" testing, then you change some code and reload the panel page it will re-run that query.

Issues may be if the endpoint isn't idempotent or is destructive etc, may lead to weird outcomes during testing/debugging.

**Comment by iway1** [comment]
I've noticed this, don't think it'd likely cause issues, but you're right would be better if it only ran queries when the user presses the execute button. 

I think there is probably a React Query setting to turn this off, probably `refetchOnReconnect: false` and/or
 `refetchOnWindowFocus: false`

**Comment by AshSimmonds** [comment]
Where would that be set, is it beyond the usual appRouter? Just tried these settings and none of them seem to matter - btw it does the re-run just when the page itself gets focus too, which my normal pages do not so it's getting that setting elsewhere.

```export const trpc = setupTRPC<AppRouter>({
    config() {
        return {
            queryClientConfig: {
                defaultOptions: {
                    queries: {
                        // staleTime: 1000 * 60 * 5, // 5 minutes
                        refetchOnWindowFocus: false,
                        retry: false,
                        refetchOnReconnect: false,
                        refetchOnMount: false,
                        retryOnMount: false,
                    },
                },
            },
            url: `${getBaseUrl()}/api/trpc`,
            transformer,
        }
    },
    ssr: false,
})```

**Comment by iway1** [comment]
That's weird I would think that would work, you could try changing it in the `ProcedureForm` component (where `useQuery` is getting called) and pass the options there directly to the hook
